# -*- coding: utf-8 -*-
"""QR_JPM_T1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G42sYDzKsK63a327pdT4zCFEpJrEgqAn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Nat_Gas.csv')
# df.head(10)
# df_date = df[:, 0]
# df_price = df[:, 1]

plt.plot(df['Dates'], df['Prices'])

